### ISSUE TITLE
Подключение к сервису

### ISSUE THREAD

**Issue by Mosokna** [oknosoft/windowbuilder-parametric#1]
Добрый день. Разбираю обработку подключения к сервису заказа подоконников. 
С подключением понятно, не пойму каким образом формировать соответствия номенклатуры.
Подскажите, если к примеру мне нужно заказать подоконник, что задавать в паре соответствия?
Нахожу в вашей базе нужный подоконник (59dc92fc-7db5-45b7-94c7-8757d4894059	УТ000001360	Подоконник пласт. КР-40-100	КР100)
Нахожу в вашей базе нужный цвет (0783a228-e244-11e3-8a4f-9cb654bba81d	119	глория/глянец)
Что должно быть вставлено?

**Comment by unpete** [comment]
В _Заказе дилера_ используется унаследованная из УПзП классификация строк заказа:
- Материал (например, заглушки) - то, что отгружается со склада и не требует обработки в цехе
- Продукция (например, подоконник) - у неё есть спецификация (исходные материалы) 

Ваш заказ может содержать как продукцию, так и материалы.
- Чтобы система при обработке запроса создала строку продукции, вашу номенклатуру необходимо сопоставить с элементом нашего справочника _Вставки_
- Для заказа материалов, вашу номенклатуру надо сопоставить с элементом нашего справочника _Номенклатура_

На текущий момент, в справочнике _Вставки_ - единственная позиция _КР100_.
Вставок будет не много: по основным группам продукции (подоконники КР, ПВХ, с Фаской, Панели)
Материалов существенно больше - список можно получить запросом к сервису или из макета обработки.

После создания заказа, сервис возвращает структуру с данными, где в табличной части будут уже не вставки, а номенклатура. Тут вам потребуется обратное преобразование, чтобы сопоставить (59dc92fc-7db5-45b7-94c7-8757d4894059	УТ000001360 Подоконник пласт. КР-40-100) с вашей номенклатурой, ссылка которой должна попасть в заказ поставщику.

Резюме:
Для продукций надо настроить два соответствия:
- Ваша номенклатура -> наши вставки для запроса в сервис
- Наша номенклатура -> ваша номенклатура для записи в вашу 1С

**Comment by unpete** [comment]
Запланировал на этой неделе сделать описание API - по какому пути, какие запросы с какими параметрами что возвращают

**Comment by Mosokna** [comment]
Евгений, немного не понял.
Что именно вы ожидаете увидеть на своей стороне.
Вот пример кода обработки.
Кеш = Новый Структура("Номенклатура, Цвет", Новый Соответствие(), Новый Соответствие(), );
Мне нужно заказать у вас подоконник - Подоконник пласт. КР-40-100
Цвет - глория/глянец

В нашей базе есть Номенклатура Подококнник КР-100 и характеристика его 11900
Как должен выглядеть код?
СоответсвиеНоменлатуры = Новый Соответствие;
СоответсвиеНоменлатуры .Вставить("Подококнник КР-100", "Подоконник пласт. КР-40-100");
СоответсвиеЦвета = Новый Соответствие;
СоответсвиеЦвета .Вставить("11900", "глория/глянец");
Кеш = Новый Структура("Номенклатура, Цвет", СоответсвиеНоменлатуры,СоответсвиеЦвета , );
Правильно я понимаю?

**Comment by unpete** [comment]
Задача из трёх частей. Решать предлагаю по отдельности.:
- Прочитать код модуля обработки - там работающий пример. Он отправляет тестовые данные в сервис, а сервис по этим данным создаёт заказ и возвращает структуру этого заказа
- Настроить соответствие ваших _номенклатур_ и _цветов_ для отправки запроса в сервис
- Настроить соответствие ваших _номенклатур_ и _характеристик_ для чтения ответа из сервиса

Если в ваших метаданных нет справочника _цвета_, соответствия в обе стороны можно настроить по характеристикам.
Сейчас дополню обработку функцией выгрузки ссылок номенклатур и характеристик вашей базы - по этим данным смогу сделать полноценный пример.

**Comment by Mosokna** [comment]
Ок. Тогда скиньте полноценный пример на почту пожалуйста, как дополните.

**Comment by Mosokna** [comment]
Спасибо, теперь попонятнее.
Подскажите
ref, number_doc, date, delivery_date, partner, production
В партнер что указывать?

**Comment by unpete** [comment]
> В партнер что указывать?

_guid контрагента_ - его должно быть видно в одном из табличных документов при нажатии на кнопку _Справочники_
Имеет смысл, если у вас есть несколько договоров с Кристаллитом от разных юрлиц.
Если заказы делаются всегда от мосокон, партнера можно не заполнять.

**Comment by Mosokna** [comment]
Евгений, подскажите пожалуйста структуру результата.
Рез = ЗапросКСервису("post", "prm/doc.calc_order/" + ДанныеДляЗаказа.ref, Кеш, ДанныеДляЗаказа);
Как понять, успешно отправилась заявка или нет.
И где можно посмотреть отправленные заявки.

**Comment by unpete** [comment]
> подскажите пожалуйста структуру результата

Дополнил описание - см. [readme](https://github.com/oknosoft/windowbuilder-parametric/blob/master/README.md)

> где можно посмотреть отправленные заявки

Заказы доступны в сервисе вне зависимости от того, созданы они человеком через браузер или автоматом запросом к микросервису. Реквизиты для подключения к https://crystallit.oknosoft.ru/?zone=25&couch_suffix=27 у вас есть

**Comment by Mosokna** [comment]
Никак не могу отправить вам запрос. Вот что возвращается.
<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.13.2</center>
</body>
</html>

**Comment by Mosokna** [comment]
Причет справочники я считать могу.
Рез = Соединение.Получить(Запрос);
А как дело доходит до отправки
		Запрос.УстановитьТелоИзСтроки(Записать_JSON(Данные));
		Рез = Соединение.ОтправитьДляОбработки(Запрос);
То ошибка.

**Comment by unpete** [comment]
Ошибку проанализирую.
Обновил файл микросервиса - учёл изменения основной ветки windowbuilder https://github.com/oknosoft/windowbuilder-parametric/commit/eaae81403be6d5c24f3202a7f1ba54362e23fe24
Сейчас заказы создаются, но ясности про _502 Bad Gateway_ пока нет.

**Comment by nmivan** [comment]
Ошибку исправили на стороне обработки для 1С, была связана с режимом совместимости.

**Comment by unpete** [comment]
Старая платформа 1С добавляла символ `bom` в тело post запроса, что мешало десериализации данных запроса.
- Запланировал доработку сервиса, чтобы он отбрасывал лишние символы
- Повысил информативность сообщений об ошибках

**Comment by Mosokna** [comment]
Добрый день. Подскажите, делаю запрос к сервису.
Рез = Новый Структура("data", ЗапросКСервису("get", "prm/cat/clrs,nom,inserts", Кеш));
Но вставки (inserts) не возвращаются. Но ведь именно во вставках содержится информация о подоконниках.

**Comment by malinovme** [comment]
Добрый день. Справочник вставок теперь объединен со справочником номенклатуры.

**Comment by Mosokna** [comment]
А можно на сайте как то отделить заказы по контрагентам. Зачем мне (Московские окна) видеть заказы других контрагентов?

**Comment by Mosokna** [comment]
И еще вопрос. Я отправил заказ. Ошибся. Отправляю еще раз. Сервис мне возвращает "Запрещено изменять отправленный заказ ab4ffb75-ae48-11e7-bc0f-00155d03e100 - его сначала нужно отозвать
". Как я могу отозвать заказ? Что для этого нужно сделать?

**Comment by unpete** [comment]
> Как я могу отозвать заказ? Что для этого нужно сделать?

Нужно отправить post запрос, указав в поле `obj_delivery_state` строку `Отозван`

**Comment by unpete** [comment]
> Зачем мне (Московские окна) видеть заказы других контрагентов?

В вашей базе (с суффиксом 0027) чужих заказов нет.
Индивидуальные базы пользователей содержат только их документы.
По ошибке, абоненты, авторизованные в своих базах, имели доступ к корневой базе - исправлено.
Суффикс подключения можно задать на странице настроек либо перейдя по ссылке вида [https://crystallit.oknosoft.ru/?zone=25&couch_suffix=xxxx], где xxxx - суффикс вашей организации

**Comment by Mosokna** [comment]
Отозвал Но после того как отозвал, и перезалил данные, у подоконников должны были измениться цвета, но все осталось как было. Может быть еще какая то процедура очистки должна была случиться?

**Comment by Mosokna** [comment]
Ошибся, наверное закешировались данные. После того как перезашел под своим суффиксом цвета поменялись в заказе.

**Comment by unpete** [comment]
Синхронизация справочников и прочих объектов, с типом кеширования ram, работает очень хорошо. Изменения объектов в сервисе или в браузере или в 1С моментально расползаются по всем, подключенным к шине данных программам.
Документы обновляются немного иначе.
Про отставание состояния документа в браузере от того, что записл сервис я знаю. Это задача с низким приоритетом.
Вы можете доверять ответу сервиса после создания заказа и получать цвета, размеры и цены оттуда.
Для заказов, созданных сервисом, браузер играет роль ведомого. Перепроверять с его помощью результат расчета особого смысла нет - лучше сделать get запрос к сервису

**Comment by Mosokna** [comment]
Добрый день. В справочнике цветов не хватает цвета 
палермо сатин (133)

**Comment by nmivan** [comment]
@Mosokna , проверяйте.

**Comment by nmivan** [comment]
@Mosokna , предлагаю создавать отдельные задачи, когда они возникают. Эта задача давно закрыта, и то, что в ней есть вопрос, видно только из почты, а у нас [flowcon](https://flowcon.js.org/).

**Comment by Mosokna** [comment]
Цвет добавился. Будем создавать отдельными.

**Comment by nmivan** [comment]
@Mosokna , спасибо!
