### ISSUE TITLE
Обработка анализа логов микросервиса

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder-parametric#14]
Реализовать в 1С

**Comment by nmivan** [comment]
Логи уже есть в микросервисе? Как их на стороне 1С посмотреть?

**Comment by unpete** [comment]
см #13

**Comment by nmivan** [comment]
[Обработка](https://github.com/oknosoft/windowbuilder-parametric/blob/master/1c/%D0%9F%D0%B0%D1%80%D0%B0%D0%BC%D0%B5%D1%82%D1%80%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9%D0%97%D0%B0%D0%BA%D0%B0%D0%B72.epf)
[Описание](https://github.com/oknosoft/windowbuilder-parametric/blob/master/1c/README.md)
