### ISSUE TITLE
Информировать об ошибке при неверной номенклатуре

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder-parametric#16]
Если в запросе к сервису вместо вставки передали номенклатуру материала или номенклатуру продукции, надо не создавать заказ, а сообщать об ошибке в запросе

**Comment by nmivan** [comment]
Надо еще чтобы возвращала ошибку, если для вставки не указана длина/высота.

**Comment by unpete** [comment]
> если для вставки не указана длина/высота

Это справедливо для Кристаллита, но в общем случае, вставка может не быть завязана на размеры.
Контроль полноты параметров правильнее поручить самой вставке - она может генерировать исключение или подмешивать в ответ информацию об ошибке

**Comment by unpete** [comment]
учтено в алгоритме + в ответ теперь подмешивается строка ошибки
