### ISSUE TITLE
Исправить ошибку с пустыми валютами

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#18]
`$p.cat.currencies.alatable` выдает 3179 записей с пустой ссылкой, и похоже из-за этого цены сервис возвращает округленные до целых знаков.

**Comment by unpete** [comment]
- При выгрузке документов установки цен из 1С, теперь в шапку подмешивается валюта
- Повторно выгрузил документы в сервис
- Доработал метод `get` у `DataManager`, чтобы он корректно обрабатывал `undefined` в качестве запрашиваемой ссылки
