### ISSUE TITLE
Разобраться с разницей в ценах

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#19]

**Comment by nmivan** [comment]
Разница возникает из-за того, что в УПЗП делается два последовательных округления - до 2 знаков, потом до 0 знаков.
В сервисе формула сразу делала округление до 0 знаков.
В результате округление цены 963.495 по двум алгоритмам приводило к разному результату - 964 и 963 соответственно.

**Comment by nmivan** [comment]
В итоге оставили алгоритм сервиса, который округляет цену до нуля знаков.

**Comment by unpete** [comment]
В пятницу звонил Леонид - просил обратить внимание на копейки.
Это я не к тому, что задачу надо переоткрывать, но у нас должна быть позиция и цены сервиса не должны сильно отличаться от 1С-ных.

**Comment by nmivan** [comment]
Ему какие цены больше нравятся?

**Comment by unpete** [comment]
Он советовался с бухгалтершей и клиентами. Хотят без копеек, но ещё больше,
хотят, чтобы было понятно происхождение цифры
