### ISSUE TITLE
Обработка тестирования цен

### ISSUE THREAD

**Issue by unpete** [oknosoft/windowbuilder-parametric#33]
Нужна обработка, которая будет создавать два заказа: один с помощью сервиса, другой - внутри 1С через "добавить продукцию список" с полным набором номенклатур и допустимых для этих номенклатур цветов и размеров. Плюс, отчет по расхождениям между сформированными заказами.

**Comment by nmivan** [comment]
Не надо.

**Comment by unpete** [comment]
А почему не надо? Тестирование - наше узкое место. Сейчас мы не уверены,
что цены в сервисе такие же, как в 1с. Мы это только предполагаем, но
протестировать не можем.

**Comment by nmivan** [comment]
"Не надо" относилось к текущему моменту. Вот прямо сейчас она не нужна. Причины проблем, которые у нас были с ценами, мы нашли - разное округление и местами невыгруженные цены.
Цены ты вроде поставил в выгрузку.
На округление мы плюнули.

Если настаиваешь, оставим задачу. Я закрываю ровно для одного - чтобы эфир не засоряли.
