### ISSUE TITLE
Добавить 131 цвет

### ISSUE THREAD

**Issue by Mosokna** [oknosoft/windowbuilder-parametric#45]
Добавьте в таблицу clrs цвет 131 - софия сатин

**Comment by unpete** [comment]
В настоящий момент нет доступа к серверу 1С Кристаллита (не путать с сервером сервиса параметрических заказов - он в Германии и доступен 99,9% времени в году).
Как только в Дурыкино починят интернет - зарегистрирую цвет.

**Comment by unpete** [comment]
Все цвета в сервисе уже были зарегистрированы.
У цветов Эстера были неправильные коды, но это ни на что не влияло, для сопоставления мы используем guid, а не код или наименование.
Коды в сервисе обновил, ссылки остались прежними.
Буду признателен, если подскажете, как вы эти коды использовали.

**Comment by Mosokna** [comment]
Использую след образом. Допустим я знаю что мне нужен 131 цвет.
Считываю ваш справочник clrs и ищу там 131 код. Вижу его гуид, добавляю его в запрос к сервису.

**Comment by unpete** [comment]
Спасибо.
У цветов Эстера по инициативе поставщика были изменены коды. Это создало некоторые проблемы.
Вопрос закрываю.
