### ISSUE TITLE
Выгрузка реализаций в сервис и доступ по https

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#48]

**Comment by nmivan** [comment]
1. Должен выгружать не реализации, а вообще любые документы и справочники;
2. Должен уметь выгружать отдельно список, отдельно документы;
3. Должен выгружать объекты. Возможно, опционально.

**Comment by unpete** [comment]
1C-ную часть по реализациям + установкам цен прикрутил (раньше они выгружались только в ручном режиме). JS часть, как и договаривались - не трогаю.

**Comment by nmivan** [comment]
Закрываю, разыменование осталось, но это отдельная задача будет.
