### ISSUE TITLE
Сервис присваивает одинаковый номер разным заказам

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#5]
Пример - 2 заказа Экоокон получили номер EO000000001
ИД заказов: b0e3c5df-6890-11e7-81d7-005056aafe4c и 2bf83494-6891-11e7-81d7-005056aafe4c

**Comment by unpete** [comment]
Заберу эту задачу себе

**Comment by unpete** [comment]
https://github.com/oknosoft/windowbuilder-parametric/commit/5d327b8c7e3e60f4b14ec6d6ee3e581aca5b2e3e

Проблема возникала из-за пустой даты документа на момент присвоения номера. Он бы всегда _00000001_, т.к. в нулевом году документы отсутствовали.
