### ISSUE TITLE
Недостающие перечисления в интеграции УПзП

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#52]
Перечисления пзТипыСоединений, пзТипыОткрывания в УПзП есть, его пытается обрабатывать модификатор modifiers.js, но его нет в типовой настройке метаданных и синонимов в УПзП, а соответственно - и в метаданных сервиса.

В заказе дилера, на стороне сервиса, такое перечисление есть.

Так и должно быть? Если я добавляю их в типовую настройку синонимов, то все становится хорошо.

**Comment by unpete** [comment]
Метаданные и модификаторы сервиса ничего не знают и не должны знать про
УПзП. Рекомендуется использовать метаданные ЗД.
Состав модификаторов под твоим полным контролем.

**Comment by nmivan** [comment]
> Рекомендуется использовать метаданные ЗД.

вот в этом ошибка была, я УПзПшные метаданные подсунул.
