### ISSUE TITLE
Инструкция по подключению новых клиентов к сервису

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#6]

**Comment by unpete** [comment]
При создании-изменении заказов, теперь учитывается значение поля `obj_delivery_state` структуры запроса:
- По умолчанию, заказы создаются в статусе `Отправлен` и поступают в очередь к запуску в работу
- Если передать в поле `obj_delivery_state` значения `Черновик` или `Отозван` - заказ в очередь к запуску не попадает либо удаляется из этой очереди, если ранее он имел статус  `Отправлен`

**Comment by nmivan** [comment]
Вот [тут](https://github.com/oknosoft/windowbuilder-parametric/blob/master/how%20to%20connect.md)
