### ISSUE TITLE
Инструкция по первому запуску

### ISSUE THREAD

**Issue by Sehktel** [oknosoft/windowbuilder-parametric#64]
Здравствуйте. 
Необходима краткая инструкция по включению данного сервиса.
Репозиторий к себе забрал, обновил, собрал.
Как его запустить, указать базу данных и начать получать от сервиса данные?

**Comment by unpete** [comment]
> инструкция по включению данного сервиса

Для решения каких задач?

**Comment by Sehktel** [comment]
Целей несколько:
  1. Мы хотим получить изображение для печатных форм без размерных линий.
  Как вариант - научить данный сервис генерировать необходимые данные. 
  Т.к. от данного сервиса мы можем получать данные.
  Хотя ... правильнее будет получить эти данные от сервиса создания эскизов. 
  Тогда к нему будет тот же вопрос - как установить и начать использовать? 
  Повторить вопрос в правильной ветке?
  2. Начать с ним работать, понизив энтропию системы. И даже если не будем вносить пул реквесты, то иметь возможность остановиться отладчиком и проверить различные догадки.
  3. Хочется научиться работать именно с параметрическим построителем, чтобы снизить зависимость нового типового заказа от человеческого фактора менеджера. 
  4. Это несколько в сторону. Мы с вами обсуждали возможность создания собственного канваса для отчетов, на котором мы сможем "нарисовать" все что нам будет необходимо. 
  К примеру - попробовать подписать номера элементов и заполнений.
  Вопрос - как начать двигаться в правильную сторону?

**Comment by unpete** [comment]
> изображение для печатных форм без размерных линий

Для этого нужен сервис windowbuilder-reports, а не windowbuilder-parametric

**Comment by nmivan** [comment]
Инструкция.

1. Форкуем, скачиваем, разворачиваем;
2. npm install;
3. build;
4. базу указываем в app.settings (или в environment, не помню, можно там или нет);
5. запускаем отладку скриптом start;
6. В браузере открываем отладку по ссылке:
chrome-devtools://devtools/bundled/inspector.html?experiments=true&v8only=true&ws=127.0.0.1:9229/<идентификатор>

<идентификатор> сообщает скрипт, когда запускается отладка. После каждого перезапуска идентификатор меняется, надо заново в браузере запускать.
7. Делаем запросы к сервису.

Запросы проще всего начать делать из 1С, обработкой, которая есть в репозитории.
В макете "Подключение" пишем примерно так:
"scheme": "http",
  "host": "localhost",
  "port": 3000,
  "login": "login",
  "password": "password",
  "suffix": "0000"

**Comment by nmivan** [comment]
@Sehktel , я вам инструкцию написал, вопросы остались?

**Comment by Sehktel** [comment]
@nmivan вопросов пока нет.

**Comment by Sehktel** [comment]
```bash
npm start

> windowbuilder-parametric@2.0.237 start /home/suhov/Work/Git/windowbuilder-parametric
> node ./index

(node:14849) UnhandledPromiseRejectionWarning: ReferenceError: $p is not defined
    at Function.fix_collection (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-core/index.js:924:58)
    at CchProperties._fix_plain (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-core/index.js:937:13)
    at new CatObj (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-core/index.js:1008:12)
    at new CchProperties (/home/suhov/Work/Git/windowbuilder-parametric/index.js:8228:3)
    at ChartOfCharacteristicManager.obj_constructor (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-core/index.js:1425:11)
    at ChartOfCharacteristicManager.load_array (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-core/index.js:1724:16)
    at AdapterPouch.load_changes (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-pouchdb/index.js:1221:27)
    at local.ram.allDocs (/home/suhov/Work/Git/windowbuilder-parametric/node_modules/metadata-pouchdb/index.js:355:23)
    at /home/suhov/Work/Git/windowbuilder-parametric/node_modules/pouchdb-utils/lib/index.js:128:9
    at <anonymous>
(node:14849) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:14849) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

```

Очень смущает  ``` bash $p is not defined ```
С чем это может быть связано?

**Comment by unpete** [comment]
> С чем это может быть связано

С неактуальными файлами metadata-core, конечно.
