### ISSUE TITLE
Инструкция по настройке соответствия номенклатуры

### ISSUE THREAD

**Issue by nmivan** [oknosoft/windowbuilder-parametric#7]

**Comment by unpete** [comment]
- При запросе справочников из сервиса, теперь в одном списке возвращаются номенклатуры заглушек и вставки продукций
- Номенклатуры продукций с нелепыми нелепыми размерами скрыты от клиентов сервиса
- Ответ сервиса о составе заказа для продукций возвращает guid родительской вставки, а не guid номенклатуры

**Comment by unpete** [comment]
Изменён внутренний путь к таблицам соответствий в сервисе.
Внешний интерфейс (_/prm/store/:ref_) не поменялся, но созданные ранее соответствия придется пересоздать повторно

**Comment by nmivan** [comment]
Вот [тут](https://github.com/oknosoft/windowbuilder-parametric/blob/master/%D0%98%D0%BD%D1%81%D1%82%D1%80%D1%83%D0%BA%D1%86%D0%B8%D1%8F%20%D0%BF%D0%BE%20%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B5%20%D1%81%D0%BE%D0%BE%D1%82%D0%B2%D0%B5%D1%82%D1%81%D1%82%D0%B2%D0%B8%D0%B9.md)

**Comment by unpete** [comment]
еще бы обработку для типовых 1С в [эту папку](https://github.com/oknosoft/windowbuilder-parametric/tree/master/1c) засунуть

**Comment by nmivan** [comment]
Да, разумеется. Сведу с твоей и выложу.
