### ISSUE TITLE
Не корректно работает соответствие.

### ISSUE THREAD

**Issue by IgorUrinev** [oknosoft/windowbuilder-parametric#73]
![screen](https://user-images.githubusercontent.com/26577652/47200587-6eeaf780-d37f-11e8-806c-1fd4c42bd932.jpeg)
Соответствие настроено правильно.
А в заказе Кристаллита выписывается заглушка вместо соединителя.

**Comment by nmivan** [comment]
Можете сделать скриншот пошире, чтобы влезло поле ref?

**Comment by IgorUrinev** [comment]
![screen](https://user-images.githubusercontent.com/26577652/47207634-64872880-d394-11e8-8d8b-b67837429748.jpeg)

**Comment by nmivan** [comment]
Подскажите ваш номер заказа, в котором произошла подмена, и когда его отправляли. Я посмотрю в логах.
И еще вопрос: вы модифицировали обработку для отправки заказов?

**Comment by IgorUrinev** [comment]
number_doc | СФ000000072
number_internal | 00000009683
153 позиция
Дорабатывали, но только касаемо размеров.

**Comment by nmivan** [comment]
Лог говорит следующее.

1. Вы отправили заказ 00000009683 18.10.2018 15:22:03.
Позиция № 153 в нем:
{
			"nom": "165b1b66-417e-11e7-aafb-c92f892df045",
			"clr": "5cecb63c-8dff-4062-b56c-75928c1ff0bf",
			"len": 850,
			"height": 150,
			"quantity": 1,
			"note": "15396831853102410|1853-10;24.10",
			"НомерСтрокиЗаказа": 153
		}
Это подоконник КР-40.

Торцевой соединитель там тоже присутствует, строка № 277:
{
			"nom": "fd9b70f8-d71f-11e1-82ef-000c2911ac50",
			"clr": "",
			"len": 0,
			"height": 0,
			"quantity": 1,
			"note": "27796832401102510|2401-10СРП;25.10",
			"НомерСтрокиЗаказа": 277
		}

В запросе вы указали "obj_delivery_state": "Черновик"

2. Этот же заказ вы отправили 18.10.2018 15:22:53.
Строка № 153 точно такая же:
{
			"nom": "165b1b66-417e-11e7-aafb-c92f892df045",
			"clr": "5cecb63c-8dff-4062-b56c-75928c1ff0bf",
			"len": 850,
			"height": 150,
			"quantity": 1,
			"note": "15396831853102410|1853-10;24.10",
			"НомерСтрокиЗаказа": 153
		}

Торцевой соединитель на том же месте:
{
			"nom": "fd9b70f8-d71f-11e1-82ef-000c2911ac50",
			"clr": "",
			"len": 0,
			"height": 0,
			"quantity": 1,
			"note": "27796832401102510|2401-10СРП;25.10",
			"НомерСтрокиЗаказа": 277
		}

В запросе вы указали "obj_delivery_state": "Отправлен"

3. Затем, в 16:17:51 вы снова отправили этот заказ, но получили ответ сервиса: "Запрещено изменять проведенный заказ 3b61566d-d2cf-11e8-a267-00155d006402"

Причина - то, что в предыдущем запросе вы указали "obj_delivery_state": "Отправлен", заказ стал проведенным и менять его стало нельзя.

В вашем запросе уже были изменения.
Строка № 153:
{
			"nom": "84e54f69-b507-11e1-a7d7-1c6f65483aba",
			"clr": "",
			"len": 0,
			"height": 0,
			"quantity": 2,
			"note": "15396832407102510|2407-10;25.10",
			"НомерСтрокиЗаказа": 153
		}
Здесь номенклатура - тот самый "Торцевой соединитель 150/180 700мм белый".

Но сервис этот запрос отклонил.

Т.е. подмены никакой не было, просто начиная с третьего запроса вы получали ответ "Запрещено изменять проведенный заказ 3b61566d-d2cf-11e8-a267-00155d006402".

Наверное, вам нужно чутка пересмотреть логику отправки запросов, чтобы не прилетали изменения проведенных заказов.

Кстати, смотреть логи вы можете самостоятельно, если пользуетесь нашей обработкой (кнопка Еще - Анализ логов). Там видны все запросы, которые вы отправили, и ответы, которые дал сервис.

**Comment by IgorUrinev** [comment]
Спасибо. Посмотрю логи. Просто это уже второй заказ. Может снабжение как то не так отправляет.
