### ISSUE TITLE
Получение данных проблема

### ISSUE THREAD

**Issue by Mosokna** [oknosoft/windowbuilder-parametric#75]
Добрый день, у нас возникла проблема при получении данных.
Метод get работает, а при post возникает ошибка.

Делаем запрос.
Рез = Новый Структура("data", ЗапросКСервису("post", "prm/docs/list", Кеш, Селектор, Ложь));

Возвращается Name or password is incorrect.
Данные для пождключения
  "scheme": "https",
  "host": "crystallit.oknosoft.ru",
  "port": 443,
  "login": "mosokna",
  "password": "********"(пароль скрыл),
  "suffix": "27"

**Comment by unpete** [comment]
Спасибо, разберёмся

**Comment by unpete** [comment]
Полностью выкинул [кеширование авторизации](https://github.com/oknosoft/windowbuilder-parametric/commit/c1afaaa4dd643bf2556f279778c4ed52787c3cd8).
Просьба проверить. Если не поможет - продолжу отладку.

**Comment by Mosokna** [comment]
Заработало, спасибо
